# Generated by Django 5.2.9 on 2026-01-29 00:46 (squashed from 0001–0013)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('corp_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='고유번호')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='회사명')),
                ('business_type_code', models.CharField(blank=True, max_length=10, verbose_name='업종코드')),
                ('business_type_name', models.CharField(blank=True, max_length=50, verbose_name='업종명')),
                ('bond_yield_5y', models.FloatField(default=0.0, verbose_name='채권수익률(5년)')),
                ('passed_all_filters', models.BooleanField(default=False, verbose_name='전체필터통과')),
                ('filter_operating_income', models.BooleanField(default=False, verbose_name='영업이익필터')),
                ('filter_net_income', models.BooleanField(default=False, verbose_name='당기순이익필터')),
                ('filter_revenue_cagr', models.BooleanField(default=False, verbose_name='매출액CAGR필터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('last_collected_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막수집일시')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('filter_roe', models.BooleanField(default=False, verbose_name='ROE필터')),
                ('memo_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='메모수정일시')),
                ('filter_operating_margin', models.BooleanField(default=False, verbose_name='영업이익률필터')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사들',
                'db_table': 'company',
                'indexes': [models.Index(fields=['corp_code'], name='company_corp_co_908e09_idx')],
            },
        ),
        migrations.CreateModel(
            name='BondYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_value', models.FloatField(default=0.0, verbose_name='채권수익률(5년)')),
                ('collected_at', models.DateTimeField(verbose_name='수집일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '채권수익률',
                'verbose_name_plural': '채권수익률',
                'db_table': 'bond_yield',
            },
        ),
        migrations.CreateModel(
            name='ApiCallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('dart_calls', models.IntegerField(default=0, verbose_name='DART API 호출 횟수')),
                ('ecos_calls', models.IntegerField(default=0, verbose_name='ECOS API 호출 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'API 호출 통계',
                'verbose_name_plural': 'API 호출 통계들',
                'db_table': 'api_call_stats',
                'indexes': [models.Index(fields=['date'], name='api_call_st_date_24bcea_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '즐겨찾기그룹',
                'verbose_name_plural': '즐겨찾기그룹들',
                'db_table': 'favorite_group',
                'indexes': [models.Index(fields=['name'], name='favorite_gr_name_447650_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apps.company', verbose_name='회사')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apps.favoritegroup', verbose_name='그룹')),
            ],
            options={
                'verbose_name': '즐겨찾기',
                'verbose_name_plural': '즐겨찾기들',
                'db_table': 'favorite',
                'indexes': [models.Index(fields=['group', 'company'], name='favorite_group_i_fb7553_idx'), models.Index(fields=['company'], name='favorite_company_4fe7d1_idx')],
                'unique_together': {('group', 'company')},
            },
        ),
        migrations.CreateModel(
            name='YearlyFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='사업연도')),
                ('revenue', models.BigIntegerField(default=0, verbose_name='매출액')),
                ('operating_income', models.BigIntegerField(default=0, verbose_name='영업이익')),
                ('net_income', models.BigIntegerField(default=0, verbose_name='당기순이익')),
                ('total_assets', models.BigIntegerField(default=0, verbose_name='자산총계')),
                ('total_equity', models.BigIntegerField(default=0, verbose_name='자본총계')),
                ('gross_profit_margin', models.FloatField(default=0.0, verbose_name='매출총이익률')),
                ('selling_admin_expense_ratio', models.FloatField(default=0.0, verbose_name='판관비율')),
                ('roe', models.FloatField(default=0.0, verbose_name='ROE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_data', to='apps.company', verbose_name='회사')),
                ('fcf', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='자유현금흐름')),
                ('roic', models.FloatField(blank=True, default=0.0, null=True, verbose_name='투하자본수익률')),
                ('wacc', models.FloatField(blank=True, default=0.0, null=True, verbose_name='가중평균자본비용')),
                ('operating_margin', models.FloatField(default=0.0, verbose_name='영업이익률')),
            ],
            options={
                'verbose_name': '년도별재무데이터',
                'verbose_name_plural': '년도별재무데이터들',
                'db_table': 'yearly_financial_data',
                'indexes': [models.Index(fields=['company', 'year'], name='yearly_fina_company_466817_idx'), models.Index(fields=['year'], name='yearly_fina_year_366d2e_idx')],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='사업연도')),
                ('quarter', models.IntegerField(verbose_name='분기')),
                ('reprt_code', models.CharField(max_length=10, verbose_name='보고서코드')),
                ('rcept_no', models.CharField(blank=True, max_length=14, verbose_name='접수번호')),
                ('revenue', models.BigIntegerField(default=0, verbose_name='매출액')),
                ('operating_income', models.BigIntegerField(default=0, verbose_name='영업이익')),
                ('net_income', models.BigIntegerField(default=0, verbose_name='당기순이익')),
                ('total_assets', models.BigIntegerField(default=0, verbose_name='자산총계')),
                ('total_equity', models.BigIntegerField(default=0, verbose_name='자본총계')),
                ('operating_margin', models.FloatField(default=0.0, verbose_name='영업이익률')),
                ('roe', models.FloatField(default=0.0, verbose_name='ROE')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_data', to='apps.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '분기별재무데이터',
                'verbose_name_plural': '분기별재무데이터들',
                'db_table': 'quarterly_financial_data',
                'indexes': [models.Index(fields=['company', 'year', 'quarter'], name='quarterly_f_company_58e834_idx'), models.Index(fields=['year', 'quarter'], name='quarterly_f_year_d2e899_idx')],
                'unique_together': {('company', 'year', 'quarter')},
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name'], name='company_company_01255b_idx'),
        ),
        migrations.AddField(
            model_name='company',
            name='latest_annual_rcept_no',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='최근사업보고서접수번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='latest_annual_report_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='최근사업보고서연도'),
        ),
    ]
