# Generated by Django 5.2.9 on 2025-12-30 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('corp_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='고유번호')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='회사명')),
                ('business_type_code', models.CharField(blank=True, max_length=10, verbose_name='업종코드')),
                ('business_type_name', models.CharField(blank=True, max_length=50, verbose_name='업종명')),
                ('bond_yield_5y', models.FloatField(default=0.0, verbose_name='채권수익률(5년)')),
                ('passed_all_filters', models.BooleanField(default=False, verbose_name='전체필터통과')),
                ('filter_operating_income', models.BooleanField(default=False, verbose_name='영업이익필터')),
                ('filter_net_income', models.BooleanField(default=False, verbose_name='당기순이익필터')),
                ('filter_revenue_cagr', models.BooleanField(default=False, verbose_name='매출액CAGR필터')),
                ('filter_total_assets_operating_income_ratio', models.BooleanField(default=False, verbose_name='총자산영업이익률필터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사들',
                'db_table': 'company',
                'indexes': [models.Index(fields=['corp_code'], name='company_corp_co_908e09_idx')],
            },
        ),
        migrations.CreateModel(
            name='YearlyFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='사업연도')),
                ('revenue', models.BigIntegerField(default=0, verbose_name='매출액')),
                ('operating_income', models.BigIntegerField(default=0, verbose_name='영업이익')),
                ('net_income', models.BigIntegerField(default=0, verbose_name='당기순이익')),
                ('total_assets', models.BigIntegerField(default=0, verbose_name='자산총계')),
                ('total_equity', models.BigIntegerField(default=0, verbose_name='자본총계')),
                ('gross_profit_margin', models.FloatField(default=0.0, verbose_name='매출총이익률')),
                ('selling_admin_expense_ratio', models.FloatField(default=0.0, verbose_name='판관비율')),
                ('total_assets_operating_income_ratio', models.FloatField(default=0.0, verbose_name='총자산영업이익률')),
                ('roe', models.FloatField(default=0.0, verbose_name='ROE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_data', to='apps.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '년도별재무데이터',
                'verbose_name_plural': '년도별재무데이터들',
                'db_table': 'yearly_financial_data',
                'indexes': [models.Index(fields=['company', 'year'], name='yearly_fina_company_466817_idx'), models.Index(fields=['year'], name='yearly_fina_year_366d2e_idx')],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
