# Generated by Django 5.2.9 on 2025-12-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_value', models.FloatField(default=0.0, verbose_name='채권수익률(5년)')),
                ('collected_at', models.DateTimeField(verbose_name='수집일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '채권수익률',
                'verbose_name_plural': '채권수익률',
                'db_table': 'bond_yield',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='last_collected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막수집일시'),
        ),
    ]
