# Generated by Django 5.2.9 on 2026-01-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bond_yield_5y',
        ),
        migrations.RemoveField(
            model_name='company',
            name='business_type_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='business_type_name',
        ),
        migrations.RemoveField(
            model_name='yearlyfinancialdata',
            name='gross_profit_margin',
        ),
        migrations.RemoveField(
            model_name='yearlyfinancialdata',
            name='selling_admin_expense_ratio',
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='interest_bearing_debt',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='이자부채'),
        ),
    ]
