# Generated by Django 6.0.1 on 2026-02-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_company_bond_yield_5y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyfinancialdata',
            name='net_income',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='당기순이익'),
        ),
        migrations.AlterField(
            model_name='yearlyfinancialdata',
            name='operating_income',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='영업이익'),
        ),
        migrations.AlterField(
            model_name='yearlyfinancialdata',
            name='operating_margin',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='영업이익률'),
        ),
        migrations.AlterField(
            model_name='yearlyfinancialdata',
            name='revenue',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='매출액'),
        ),
        migrations.AlterField(
            model_name='yearlyfinancialdata',
            name='roe',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='ROE'),
        ),
        migrations.AlterField(
            model_name='yearlyfinancialdata',
            name='total_assets',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='자산총계'),
        ),
        migrations.AlterField(
            model_name='yearlyfinancialdata',
            name='total_equity',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='자본총계'),
        ),
    ]
