# Generated by Django 5.2.9 on 2026-01-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_bondyield_company_last_collected_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('dart_calls', models.IntegerField(default=0, verbose_name='DART API 호출 횟수')),
                ('ecos_calls', models.IntegerField(default=0, verbose_name='ECOS API 호출 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'API 호출 통계',
                'verbose_name_plural': 'API 호출 통계들',
                'db_table': 'api_call_stats',
                'indexes': [models.Index(fields=['date'], name='api_call_st_date_24bcea_idx')],
            },
        ),
    ]
