# Generated by Django 5.2.9 on 2026-01-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_apicallstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='fcf',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='자유현금흐름'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='roic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='투하자본수익률'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='wacc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='가중평균자본비용'),
        ),
    ]
