# Generated by Django 6.0.1 on 2026-02-18 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_add_nullable_to_yearly_financial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='capital_stock',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='자본금'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='current_assets',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='유동자산'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='current_liabilities',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='유동부채'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='noncurrent_assets',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='비유동자산'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='noncurrent_liabilities',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='비유동부채'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='profit_before_tax',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='법인세차감전순이익'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='retained_earnings',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='이익잉여금'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='total_liabilities',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='부채총계'),
        ),
        migrations.CreateModel(
            name='YearlyFinancialIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='사업연도')),
                ('idx_code', models.CharField(max_length=20, verbose_name='지표코드')),
                ('idx_val', models.FloatField(blank=True, null=True, verbose_name='지표값')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_indicators', to='apps.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '연도별재무지표',
                'verbose_name_plural': '연도별재무지표들',
                'db_table': 'yearly_financial_indicator',
                'indexes': [models.Index(fields=['company', 'year'], name='yearly_fina_company_527c94_idx'), models.Index(fields=['idx_code'], name='yearly_fina_idx_cod_0a8a98_idx')],
                'unique_together': {('company', 'year', 'idx_code')},
            },
        ),
    ]
