# Generated by Django 6.0.1 on 2026-02-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_multi_company_yearly_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyfinancialindicator',
            name='idx_nm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지표명'),
        ),
    ]
