# Generated by Django 5.2.9 on 2026-01-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_add_memo_and_calculated_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='revenue_cagr',
            field=models.FloatField(blank=True, null=True, verbose_name='매출액CAGR'),
        ),
    ]
