# Generated by Django 6.0 on 2026-01-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_company_revenue_cagr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='revenue_cagr',
        ),
    ]
