# Generated by Django 6.0.1 on 2026-02-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_add_idx_nm_to_yearly_financial_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='dividend_paid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='배당금지급'),
        ),
    ]
