# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_add_dividend_paid_to_yearly_financial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='debt_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='부채비율'),
        ),
    ]
