# Generated by Django 6.0 on 2026-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_company_revenue_cagr'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='filter_roe',
            field=models.BooleanField(default=False, verbose_name='ROE필터'),
        ),
    ]

