# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_add_debt_ratio_to_yearly_financial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='cash_and_cash_equivalents',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='현금및현금성자산'),
        ),
    ]
