# Generated by Django 5.2.9 on 2026-01-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_add_roe_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='memo_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='메모수정일시'),
        ),
    ]
