# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_add_cash_and_cash_equivalents'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='ev',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='기업가치'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='invested_capital',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='투하자본'),
        ),
    ]
