# Generated by Django 5.2.9 on 2026-01-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_add_memo_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '즐겨찾기그룹',
                'verbose_name_plural': '즐겨찾기그룹들',
                'db_table': 'favorite_group',
                'indexes': [models.Index(fields=['name'], name='favorite_gr_name_447650_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apps.company', verbose_name='회사')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apps.favoritegroup', verbose_name='그룹')),
            ],
            options={
                'verbose_name': '즐겨찾기',
                'verbose_name_plural': '즐겨찾기들',
                'db_table': 'favorite',
                'indexes': [models.Index(fields=['group', 'company'], name='favorite_group_i_fb7553_idx'), models.Index(fields=['company'], name='favorite_company_4fe7d1_idx')],
                'unique_together': {('group', 'company')},
            },
        ),
    ]
