# Generated by Django 5.2.9 on 2026-01-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_favoritegroup_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='filter_total_assets_operating_income_ratio',
        ),
        migrations.RemoveField(
            model_name='yearlyfinancialdata',
            name='total_assets_operating_income_ratio',
        ),
        migrations.AddField(
            model_name='company',
            name='filter_operating_margin',
            field=models.BooleanField(default=False, verbose_name='영업이익률필터'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='operating_margin',
            field=models.FloatField(default=0.0, verbose_name='영업이익률'),
        ),
    ]
