# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_add_ev_invested_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='passed_second_filter',
            field=models.BooleanField(default=False, verbose_name='2차필터통과'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['passed_all_filters', 'passed_second_filter'], name='company_passed_idx'),
        ),
    ]
