# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_add_passed_second_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='noncontrolling_interest',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='비지배지분'),
        ),
    ]
