# Generated by Django 5.2.9 on 2026-01-27 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_change_total_assets_operating_income_ratio_to_operating_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='사업연도')),
                ('quarter', models.IntegerField(verbose_name='분기')),
                ('reprt_code', models.CharField(max_length=10, verbose_name='보고서코드')),
                ('rcept_no', models.CharField(blank=True, max_length=14, verbose_name='접수번호')),
                ('revenue', models.BigIntegerField(default=0, verbose_name='매출액')),
                ('operating_income', models.BigIntegerField(default=0, verbose_name='영업이익')),
                ('net_income', models.BigIntegerField(default=0, verbose_name='당기순이익')),
                ('total_assets', models.BigIntegerField(default=0, verbose_name='자산총계')),
                ('total_equity', models.BigIntegerField(default=0, verbose_name='자본총계')),
                ('operating_margin', models.FloatField(default=0.0, verbose_name='영업이익률')),
                ('roe', models.FloatField(default=0.0, verbose_name='ROE')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_data', to='apps.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '분기별재무데이터',
                'verbose_name_plural': '분기별재무데이터들',
                'db_table': 'quarterly_financial_data',
                'indexes': [models.Index(fields=['company', 'year', 'quarter'], name='quarterly_f_company_58e834_idx'), models.Index(fields=['year', 'quarter'], name='quarterly_f_year_d2e899_idx')],
                'unique_together': {('company', 'year', 'quarter')},
            },
        ),
    ]
