# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_add_noncontrolling_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='시가총액'),
        ),
        migrations.AddField(
            model_name='company',
            name='market_cap_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='시가총액조회일시'),
        ),
    ]
