# Generated by Django 5.2.9 on 2026-01-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_add_quarterly_financial_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name'], name='company_company_01255b_idx'),
        ),
    ]
