# Generated by Django 5.2.9 on 2026-01-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_add_company_name_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latest_annual_rcept_no',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='최근사업보고서접수번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='latest_annual_report_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='최근사업보고서연도'),
        ),
    ]
