# Generated by Django 6.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_add_company_market_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrxDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BAS_DD', models.CharField(max_length=8, verbose_name='기준일자')),
                ('IDX_CLSS', models.CharField(blank=True, max_length=50, null=True, verbose_name='계열구분')),
                ('IDX_NM', models.CharField(blank=True, max_length=200, null=True, verbose_name='지수명')),
                ('CLSPRC_IDX', models.CharField(blank=True, max_length=50, null=True, verbose_name='종가')),
                ('CMPPREVDD_IDX', models.CharField(blank=True, max_length=50, null=True, verbose_name='대비')),
                ('FLUC_RT', models.CharField(blank=True, max_length=50, null=True, verbose_name='등락률')),
                ('OPNPRC_IDX', models.CharField(blank=True, max_length=50, null=True, verbose_name='시가')),
                ('HGPRC_IDX', models.CharField(blank=True, max_length=50, null=True, verbose_name='고가')),
                ('LWPRC_IDX', models.CharField(blank=True, max_length=50, null=True, verbose_name='저가')),
                ('ACC_TRDVOL', models.CharField(blank=True, max_length=50, null=True, verbose_name='거래량')),
                ('ACC_TRDVAL', models.CharField(blank=True, max_length=50, null=True, verbose_name='거래대금')),
                ('MKTCAP', models.CharField(blank=True, max_length=50, null=True, verbose_name='상장시가총액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krx_daily_data', to='apps.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': 'KRX 일별데이터',
                'verbose_name_plural': 'KRX 일별데이터들',
                'db_table': 'krx_daily_data',
                'indexes': [
                    models.Index(fields=['company', 'BAS_DD'], name='krx_daily_c_bas_dd_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('company', 'BAS_DD'), name='krx_daily_company_bas_dd'),
                ],
            },
        ),
    ]
