# Generated by Django 6.0.1 on 2026-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_add_interest_expense_to_yearly_financial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='krxdailydata',
            new_name='krx_daily_d_company_033dfe_idx',
            old_name='krx_daily_c_bas_dd_idx',
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['passed_all_filters', 'company_name'], name='company_passed__25192b_idx'),
        ),
    ]
