# Generated by Django 6.0.1 on 2026-02-19 20:59

from django.db import migrations, models


def set_false_to_null(apps, schema_editor):
    Company = apps.get_model('apps', 'Company')
    Company.objects.filter(passed_second_filter=False).update(passed_second_filter=None)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_add_passed_all_filters_company_name_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='company_passed_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='passed_second_filter',
            field=models.BooleanField(default=None, null=True, verbose_name='2차필터통과'),
        ),
        migrations.RunPython(set_false_to_null, noop_reverse),
    ]
