# Generated by Django 6.0.1 on 2026-02-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_add_nullable_passed_second_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='selling_admin_expense_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='판관비율'),
        ),
    ]
