# Generated by Django 6.0 on 2026-06-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_remove_krx_daily_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='filter_revenue_cagr',
        ),
        migrations.RemoveField(
            model_name='yearlyfinancialdata',
            name='capital_stock',
        ),
        migrations.RemoveField(
            model_name='yearlyfinancialdata',
            name='profit_before_tax',
        ),
    ]
