# Generated by Django 6.0 on 2026-06-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_remove_company_filter_revenue_cagr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='altman_z',
            field=models.FloatField(blank=True, null=True, verbose_name="Altman Z''-Score"),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='altman_z_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Altman Z등급'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='sustainable_growth',
            field=models.FloatField(blank=True, null=True, verbose_name='지속가능성장률g'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='zmijewski',
            field=models.FloatField(blank=True, null=True, verbose_name='Zmijewski부실확률'),
        ),
        migrations.AddField(
            model_name='yearlyfinancialdata',
            name='zmijewski_flag',
            field=models.BooleanField(blank=True, null=True, verbose_name='Zmijewski부실경보'),
        ),
    ]
